#!/bin/bash

chmod -R 0777 /opt/textedit/bin


echo "[Desktop Entry]" > /tmp/texteditdbus.desktop
echo "Name = TextEditDbus" >> /tmp/texteditdbus.desktop
echo "Name[ru] = Текстовый редактор" >> /tmp/texteditdbus.desktop
echo "Type = Application" >> /tmp/texteditdbus.desktop
echo "NoDisplay = false" >> /tmp/texteditdbus.desktop
echo "Exec = /opt/textedit/bin/textedit" >> /tmp/texteditdbus.desktop
echo "Icon = mail-unread" >> /tmp/texteditdbus.desktop
echo "Icon[ru] = mail-unread" >> /tmp/texteditdbus.desktop
echo "X-FLY-IconContext = TextTditDbus" >> /tmp/texteditdbus.desktop
echo "X-FLY-IconContext[ru] = TextEditDbus" >> /tmp/texteditdbus.desktop
echo "Hidden = false" >> /tmp/texteditdbus.desktop
echo "Terminal = false" >> /tmp/texteditdbus.desktop
echo "StartupNotify = false" >> /tmp/texteditdbus.desktop
chmod 0777 /tmp/texteditdbus.desktop
